version: '3'

services:
  host:
    build:
      context: ./

    env_file:
      - .dev

    ports:
      - 5000:5000

    depends_on:
      - postgres
    
    volumes:
      - ./dao:/app

    command: /bin/bash -c 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5000'

  postgres:
    env_file:
      - .dev
    image: postgres
