[tool.poetry]
name = "dao-task"
version = "0.0.1"
description = ""
authors = ["Matous Kyncl <matouskyncl@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.1"
psycopg2-binary = "^2.8.6"
beautifulsoup4 = "^4.9.2"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]